#!/bin/sh

set -eu

# creating gooroom-initial-setup user if it isn't already there
if ! getent passwd gooroom-initial-setup >/dev/null; then
        adduser --system --force-badname --quiet \
            --home /var/tmp/gis --shell /bin/bash gis
        adduser gis netdev
fi

exit 0
